name: Docker Image CI
on:   # 配置触发workflow的事件
  push:
    branches:   # master分支有push时触发此workflow
      - 'main'
    tags:       # tag更新时触发此workflow
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/zsss-repository/memos:dev
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/zsss-repository/memos:dev